version: '3.9'
services:
  db:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4y7sV96vA9wv46VR
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pavel@hello.io
      PGADMIN_DEFAULT_PASSWORD:  root
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
