/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package skeleton.srping.app

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class SpringContextTest {
    @Test fun `spring context loads`() {
        assert(true)
    }
}
