/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package skeleton.spring.app

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles

@SpringBootTest
@ActiveProfiles("test")
class SpringContextTest {
    @Test fun `spring context loads`() {
        assert(true)
    }
}
